### PR TITLE
Adding ux research and initial sketches for Account Page update

### PR DESCRIPTION
**Pull request by bpdesigns**

### CODE REVIEW

**Comment by bpdesigns** [comment]
@juliaelman @nickttng In "Areas" do we want to include research reports and decks from past tickets? Or is that folder for current work?

**Comment by nickttng** [comment]
@bpdesigns Personally, I don't see `Areas` being restricted to only current work, but it would be helpful to have some kind of dates indicated in the file format, so that we can sift through which files are recent, old, etc.

**Comment by juliasolorzano** [comment]
@bpdesigns can you tell me a little bit about why these files are placed in the `Archives` folder instead of `Areas`?

**Comment by bpdesigns** [comment]
@juliaelman I was originally thinking that "Archived" indicated "completed" projects but now thinking of imagining that it means "no longer relevant" and "Areas" is for "currently relevant" projects that people might want to review. 

@nickttng Any suggestion on date convention you think we should follow? One idea would be MMDDYY on the main folder.

**Comment by juliasolorzano** [comment]
@bpdesigns good point. Let's move to `Areas` please!

**Review by juliasolorzano — CHANGES_REQUESTED** [review]
Move assets to `Areas` portion of the repo.

**Comment by nickttng** [comment]
@bpdesigns Instead of `MMDDYY`, how about `YYYY-MM-DD`? The advantage of the latter is being able to order the folders by year (most recent / oldest) first instead of month, which both `08-01-20`and `08-01-18` folders would be next to each other

**Review by juliasolorzano — APPROVED** [review]

**Comment by bpdesigns** [comment]
Good idea @nickttng - I'll update my files.

**Review by nickttng — APPROVED** [review]

**Pull request merged**
