### PR TITLE
Update design assets folder to follow P.A.R.A method

### PR DESCRIPTION
**Pull request by juliasolorzano**
This draft pull request is to propose changes for an updated structure for the login.gov design assets folder. It is based off of the team conversation on #6.

### CODE REVIEW

**Comment by nickttng** [comment]
It looks decent to start with. Do we need to get more feedback before merging? At this point it's LGTM, the update has a minimal disruption at the moment, and we'll see how we feel about it after experiencing it natively on our desktop/browser.

**Comment by bpdesigns** [comment]
Makes sense to me.

**Comment by anniehirshman-gsa** [comment]
My only suggestion would be to group issues within the Projects folder, and give the subfolders descriptive names, so that as a designer I can browse for relevant files more easily without looking up each JIRA issue.  

For example, 
```
identity-ux-assets
├── Projects
│   └── IdP
│       ├── IAL2 Full Screen Image Capture (LG-XXXX)
│       ├── IAL2 New Vendor (LG-XXXX)
│       ├── AAL3 (LG-XXXX)
│   └── Brochure Site
│   └── Partners Site
```
OR by topic only: 
```
identity-ux-assets
├── Projects
│   └── IdP
│       ├── IAL1
│       ├── IAL2
│   └── Brochure Site
│   └── Partners Site
```
Also - would the Design System be an Area or Resource?

**Comment by juliasolorzano** [comment]
@anniehirshman-gsa thank you for this feedback! I am going to go ahead and merge in as-is for now, but am going to schedule time for us to discuss a second iteration 💯

**Comment by anniehirshman-gsa** [comment]
Hey @juliaelman !  Wanted to add my recent work to the Projects folder (Kantara, IAL2 Image Capture, AAL3). Can you remind me what the buckets of work are that align with our larger product vision?  

Currently there are three subfolders under Projects: Authentication, Design System, and Partnerships.  I know we discussed a few others (Identity, maybe?) but can't remember the exact terms.

**Pull request merged**
